id: 107f1d41362149d6860a78cef4b4892c
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_97-The_Chapter_on_Manjusri%E2%80%99s_Magical_Display-v1
  language: en
  author: ''
  volume: {}
